// Base types generated by `npx wrangler types` in worker-configuration.d.ts.
// Secrets (set via `wrangler secret put`) are declared here.
// Vars are widened from literal types to string since they differ per environment.
export interface Env extends Omit<Cloudflare.Env, "BETTER_AUTH_URL" | "CF_ACCOUNT_ID" | "WORKER_NAME" | "PASSKEY_ENABLED" | "ADMIN_EMAILS"> {
  BETTER_AUTH_URL: string;
  CF_ACCOUNT_ID?: string;
  BETTER_AUTH_SECRET: string;
  CF_API_TOKEN?: string;
  ADMIN_EMAILS?: string;
  WORKER_NAME?: string;
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;
  MICROSOFT_CLIENT_ID?: string;
  MICROSOFT_CLIENT_SECRET?: string;
  DISCORD_CLIENT_ID?: string;
  DISCORD_CLIENT_SECRET?: string;
  PASSKEY_ENABLED?: string;
}
